github_url: https://github.com/StevenLambion/SwiftDux
documentation:
  - Guides/*.md
custom_categories:
  - name: "Documentation"
    children:
      - "Installation"
      - "Getting Started"
      - "Persisting State"
  - name: State
    children:
      - StateType
      - IdentifiableState
      - OrderedState
  - name: Actions
    children:
      - Action
      - ActionPlan
      - ActionDispatcher
      - RunnableAction
      - EmptyAction
      - SendAction
  - name: Store
    children:
      - Store
      - StoreProxy
      - StoreAction
  - name: Reducer
    children:
      - Reducer
      - CompositeReducer
  - name: Middleware
    children:
      - Middleware
      - CompositeMiddleware
      - HandleActionMiddleware
  - name: SwiftUI
    children:
      - View
      - MappedState
      - MappedDispatch
      - ConnectableView
      - ActionBinder
      - ActionBinding
